export const categoryActionTypes = {
  CATEGORY_REQUEST_INITIATED: "CATEGORY_REQUEST_INITIATED",
  CATEGORY_FIND_ALL_REQUEST: "CATEGORY_FIND_ALL_REQUEST",
  CATEGORY_FIND_ALL_REQUEST_SUCCEED: "CATEGORY_FIND_ALL_REQUEST_SUCCEED",
  CATEGORY_FIND_ALL_REQUEST_FAILED: "CATEGORY_FIND_ALL_REQUEST_FAILED",
  CATEGORY_FIND_BY_ID_REQUEST: "CATEGORY_FIND_ALL_REQUEST",
  CATEGORY_FIND_BY_ID_REQUEST_SUCCEED: "CATEGORY_FIND_ALL_REQUEST_SUCCEED",
  CATEGORY_FIND_BY_ID_REQUEST_FAILED: "CATEGORY_FIND_ALL_REQUEST_FAILED",
  CATEGORY_QUERY_REQUEST: "CATEGORY_QUERY_REQUEST",
  CATEGORY_QUERY_REQUEST_SUCCEED: "CATEGORY_QUERY_REQUEST_SUCCEED",
  CATEGORY_QUERY_REQUEST_FAILED: "CATEGORY_QUERY_REQUEST_FAILED"
};

export const itemActionTypes = {
  ITEM_REQUEST_INITIATED: "ITEM_REQUEST_INITIATED",
  ITEM_FIND_ALL_REQUEST: "ITEM_FIND_ALL_REQUEST",
  ITEM_FIND_ALL_REQUEST_SUCCEED: "ITEM_FIND_ALL_REQUEST_SUCCEED",
  ITEM_FIND_ALL_REQUEST_FAILED: "ITEM_FIND_ALL_REQUEST_FAILED",
  ITEM_FIND_BY_ID_REQUEST: "ITEM_FIND_ALL_REQUEST",
  ITEM_FIND_BY_ID_REQUEST_SUCCEED: "ITEM_FIND_ALL_REQUEST_SUCCEED",
  ITEM_FIND_BY_ID_REQUEST_FAILED: "ITEM_FIND_ALL_REQUEST_FAILED",
  ITEM_QUERY_REQUEST: "ITEM_QUERY_REQUEST",
  ITEM_QUERY_REQUEST_SUCCEED: "ITEM_QUERY_REQUEST_SUCCEED",
  ITEM_QUERY_REQUEST_FAILED: "ITEM_QUERY_REQUEST_FAILED"
};

export const cartItemActionTypes = {
  CARTITEM_REQUEST_INITIATED: "CARTITEM_REQUEST_INITIATED",
  CARTITEM_QUERY_REQUEST: "CARTITEM_QUERY_REQUEST",
  CARTITEM_QUERY_REQUEST_SUCCEED: "CARTITEM_QUERY_REQUEST_SUCCEED",
  CARTITEM_QUERY_REQUEST_FAILED: "CARTITEM_QUERY_REQUEST_FAILED",
  CARTITEM_CREATE_REQUEST: "CARTITEM_CREATE_REQUEST",
  CARTITEM_CREATE_REQUEST_SUCCEED: "CARTITEM_CREATE_REQUEST_SUCCEED",
  CARTITEM_CREATE_REQUEST_FAILED: "CARTITEM_CREATE_REQUEST_FAILED",
  CARTITEM_UPDATE_REQUEST: "CARTITEM_UPDATE_REQUEST",
  CARTITEM_UPDATE_REQUEST_SUCCEED: "CARTITEM_UPDATE_REQUEST_SUCCEED",
  CARTITEM_UPDATE_REQUEST_FAILED: "CARTITEM_UPDATE_REQUEST_FAILED",
  CARTITEM_DELETE_REQUEST: "CARTITEM_DELETE_REQUEST",
  CARTITEM_DELETE_REQUEST_SUCCEED: "CARTITEM_DELETE_REQUEST_SUCCEED",
  CARTITEM_DELETE_REQUEST_FAILED: "CARTITEM_DELETE_REQUEST_FAILED"
};

export const productActionTypes = {
  PRODUCT_REQUEST_INITIATED: "PRODUCT_REQUEST_INITIATED",
  PRODUCT_FIND_ALL_REQUEST: "PRODUCT_FIND_ALL_REQUEST",
  PRODUCT_FIND_ALL_REQUEST_SUCCEED: "PRODUCT_FIND_ALL_REQUEST_SUCCEED",
  PRODUCT_FIND_ALL_REQUEST_FAILED: "PRODUCT_FIND_ALL_REQUEST_FAILED",
  PRODUCT_FIND_BY_ID_REQUEST: "PRODUCT_FIND_ALL_REQUEST",
  PRODUCT_FIND_BY_ID_REQUEST_SUCCEED: "PRODUCT_FIND_ALL_REQUEST_SUCCEED",
  PRODUCT_FIND_BY_ID_REQUEST_FAILED: "PRODUCT_FIND_ALL_REQUEST_FAILED",
  PRODUCT_QUERY_REQUEST: "PRODUCT_QUERY_REQUEST",
  PRODUCT_QUERY_REQUEST_SUCCEED: "PRODUCT_QUERY_REQUEST_SUCCEED",
  PRODUCT_QUERY_REQUEST_FAILED: "PRODUCT_QUERY_REQUEST_FAILED"
};

export const productBrandActionTypes = {
  PRODUCTBRAND_REQUEST_INITIATED: "PRODUCTBRAND_REQUEST_INITIATED",
  PRODUCTBRAND_FIND_ALL_REQUEST: "PRODUCTBRAND_FIND_ALL_REQUEST",
  PRODUCTBRAND_FIND_ALL_REQUEST_SUCCEED: "PRODUCTBRAND_FIND_ALL_REQUEST_SUCCEED",
  PRODUCTBRAND_FIND_ALL_REQUEST_FAILED: "PRODUCTBRAND_FIND_ALL_REQUEST_FAILED",
  PRODUCTBRAND_FIND_BY_ID_REQUEST: "PRODUCTBRAND_FIND_ALL_REQUEST",
  PRODUCTBRAND_FIND_BY_ID_REQUEST_SUCCEED: "PRODUCTBRAND_FIND_ALL_REQUEST_SUCCEED",
  PRODUCTBRAND_FIND_BY_ID_REQUEST_FAILED: "PRODUCTBRAND_FIND_ALL_REQUEST_FAILED",
  PRODUCTBRAND_QUERY_REQUEST: "PRODUCTBRAND_QUERY_REQUEST",
  PRODUCTBRAND_QUERY_REQUEST_SUCCEED: "PRODUCTBRAND_QUERY_REQUEST_SUCCEED",
  PRODUCTBRAND_QUERY_REQUEST_FAILED: "PRODUCTBRAND_QUERY_REQUEST_FAILED"
};

export const productBrandUnitActionTypes = {
  PRODUCTBRANDUNIT_REQUEST_INITIATED: "PRODUCTBRANDUNIT_REQUEST_INITIATED",
  PRODUCTBRANDUNIT_FIND_ALL_REQUEST: "PRODUCTBRANDUNIT_FIND_ALL_REQUEST",
  PRODUCTBRANDUNIT_FIND_ALL_REQUEST_SUCCEED: "PRODUCTBRANDUNIT_FIND_ALL_REQUEST_SUCCEED",
  PRODUCTBRANDUNIT_FIND_ALL_REQUEST_FAILED: "PRODUCTBRANDUNIT_FIND_ALL_REQUEST_FAILED",
  PRODUCTBRANDUNIT_FIND_BY_ID_REQUEST: "PRODUCTBRANDUNIT_FIND_ALL_REQUEST",
  PRODUCTBRANDUNIT_FIND_BY_ID_REQUEST_SUCCEED: "PRODUCTBRANDUNIT_FIND_ALL_REQUEST_SUCCEED",
  PRODUCTBRANDUNIT_FIND_BY_ID_REQUEST_FAILED: "PRODUCTBRANDUNIT_FIND_ALL_REQUEST_FAILED",
  PRODUCTBRANDUNIT_QUERY_REQUEST: "PRODUCTBRANDUNIT_QUERY_REQUEST",
  PRODUCTBRANDUNIT_QUERY_REQUEST_SUCCEED: "PRODUCTBRANDUNIT_QUERY_REQUEST_SUCCEED",
  PRODUCTBRANDUNIT_QUERY_REQUEST_FAILED: "PRODUCTBRANDUNIT_QUERY_REQUEST_FAILED"
};

export const sellerProductBrandUnitActionTypes = {
  SELLERPRODUCTBRANDUNIT_REQUEST_INITIATED: "SELLERPRODUCTBRANDUNIT_REQUEST_INITIATED",
  SELLERPRODUCTBRANDUNIT_FIND_ALL_REQUEST: "SELLERPRODUCTBRANDUNIT_FIND_ALL_REQUEST",
  SELLERPRODUCTBRANDUNIT_FIND_ALL_REQUEST_SUCCEED:
    "SELLERPRODUCTBRANDUNIT_FIND_ALL_REQUEST_SUCCEED",
  SELLERPRODUCTBRANDUNIT_FIND_ALL_REQUEST_FAILED: "SELLERPRODUCTBRANDUNIT_FIND_ALL_REQUEST_FAILED",
  SELLERPRODUCTBRANDUNIT_FIND_BY_ID_REQUEST: "SELLERPRODUCTBRANDUNIT_FIND_ALL_REQUEST",
  SELLERPRODUCTBRANDUNIT_FIND_BY_ID_REQUEST_SUCCEED:
    "SELLERPRODUCTBRANDUNIT_FIND_ALL_REQUEST_SUCCEED",
  SELLERPRODUCTBRANDUNIT_FIND_BY_ID_REQUEST_FAILED:
    "SELLERPRODUCTBRANDUNIT_FIND_ALL_REQUEST_FAILED",
  SELLERPRODUCTBRANDUNIT_QUERY_REQUEST: "SELLERPRODUCTBRANDUNIT_QUERY_REQUEST",
  SELLERPRODUCTBRANDUNIT_QUERY_REQUEST_SUCCEED: "SELLERPRODUCTBRANDUNIT_QUERY_REQUEST_SUCCEED",
  SELLERPRODUCTBRANDUNIT_QUERY_REQUEST_FAILED: "SELLERPRODUCTBRANDUNIT_QUERY_REQUEST_FAILED"
};

export const sessionActionTypes = {
  AUTHENTICATION_REQUEST_INITIATED: "AUTHENTICATION_REQUEST_INITIATED",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
  UNAUTHENTICATE_SUCCESS: "UNAUTHENTICATE_SUCCESS",
  UNAUTHENTICATE_REQUEST_INITIATED: "UNAUTHENTICATE_REQUEST_INITIATED",
  AUTHENTICATION_REQUEST_FAILED: "AUTHENTICATION_REQUEST_FAILED"
};
