export const categoryActionTypes = {
  CATEGORY_REQUEST_INITIATED: "CATEGORY_REQUEST_INITIATED",
  CATEGORY_FIND_ALL_REQUEST: "CATEGORY_FIND_ALL_REQUEST",
  CATEGORY_FIND_ALL_REQUEST_SUCCEED: "CATEGORY_FIND_ALL_REQUEST_SUCCEED",
  CATEGORY_FIND_ALL_REQUEST_FAILED: "CATEGORY_FIND_ALL_REQUEST_FAILED",
  CATEGORY_FIND_BY_ID_REQUEST: "CATEGORY_FIND_ALL_REQUEST",
  CATEGORY_FIND_BY_ID_REQUEST_SUCCEED: "CATEGORY_FIND_ALL_REQUEST_SUCCEED",
  CATEGORY_FIND_BY_ID_REQUEST_FAILED: "CATEGORY_FIND_ALL_REQUEST_FAILED",
  CATEGORY_QUERY_REQUEST: "CATEGORY_QUERY_REQUEST",
  CATEGORY_QUERY_REQUEST_SUCCEED: "CATEGORY_QUERY_REQUEST_SUCCEED",
  CATEGORY_QUERY_REQUEST_FAILED: "CATEGORY_QUERY_REQUEST_FAILED"
};

export const itemActionTypes = {
  ITEM_REQUEST_INITIATED: "ITEM_REQUEST_INITIATED",
  ITEM_FIND_ALL_REQUEST: "ITEM_FIND_ALL_REQUEST",
  ITEM_FIND_ALL_REQUEST_SUCCEED: "ITEM_FIND_ALL_REQUEST_SUCCEED",
  ITEM_FIND_ALL_REQUEST_FAILED: "ITEM_FIND_ALL_REQUEST_FAILED",
  ITEM_FIND_BY_ID_REQUEST: "ITEM_FIND_ALL_REQUEST",
  ITEM_FIND_BY_ID_REQUEST_SUCCEED: "ITEM_FIND_ALL_REQUEST_SUCCEED",
  ITEM_FIND_BY_ID_REQUEST_FAILED: "ITEM_FIND_ALL_REQUEST_FAILED",
  ITEM_QUERY_REQUEST: "ITEM_QUERY_REQUEST",
  ITEM_QUERY_REQUEST_SUCCEED: "ITEM_QUERY_REQUEST_SUCCEED",
  ITEM_QUERY_REQUEST_FAILED: "ITEM_QUERY_REQUEST_FAILED"
};

export const cartItemActionTypes = {
  CARTITEM_REQUEST_INITIATED: "CARTITEM_REQUEST_INITIATED",
  CARTITEM_QUERY_REQUEST: "CARTITEM_QUERY_REQUEST",
  CARTITEM_QUERY_REQUEST_SUCCEED: "CARTITEM_QUERY_REQUEST_SUCCEED",
  CARTITEM_QUERY_REQUEST_FAILED: "CARTITEM_QUERY_REQUEST_FAILED",
  CARTITEM_CREATE_REQUEST: "CARTITEM_CREATE_REQUEST",
  CARTITEM_CREATE_REQUEST_SUCCEED: "CARTITEM_CREATE_REQUEST_SUCCEED",
  CARTITEM_CREATE_REQUEST_FAILED: "CARTITEM_CREATE_REQUEST_FAILED",
  CARTITEM_UPDATE_REQUEST: "CARTITEM_UPDATE_REQUEST",
  CARTITEM_UPDATE_REQUEST_SUCCEED: "CARTITEM_UPDATE_REQUEST_SUCCEED",
  CARTITEM_UPDATE_REQUEST_FAILED: "CARTITEM_UPDATE_REQUEST_FAILED",
  CARTITEM_DELETE_REQUEST: "CARTITEM_DELETE_REQUEST",
  CARTITEM_DELETE_REQUEST_SUCCEED: "CARTITEM_DELETE_REQUEST_SUCCEED",
  CARTITEM_DELETE_REQUEST_FAILED: "CARTITEM_DELETE_REQUEST_FAILED"
};

export const productActionTypes = {
  PRODUCT_REQUEST_INITIATED: "PRODUCT_REQUEST_INITIATED",
  PRODUCT_FIND_BY_ID_REQUEST_INITIATED: "PRODUCT_FIND_BY_ID_REQUEST_INITIATED",
  PRODUCT_FIND_ALL_REQUEST: "PRODUCT_FIND_ALL_REQUEST",
  PRODUCT_FIND_ALL_REQUEST_SUCCEED: "PRODUCT_FIND_ALL_REQUEST_SUCCEED",
  PRODUCT_FIND_ALL_REQUEST_FAILED: "PRODUCT_FIND_ALL_REQUEST_FAILED",
  PRODUCT_FIND_BY_ID_REQUEST: "PRODUCT_FIND_ALL_REQUEST",
  PRODUCT_FIND_BY_ID_REQUEST_SUCCEED: "PRODUCT_FIND_ALL_REQUEST_SUCCEED",
  PRODUCT_FIND_BY_ID_REQUEST_FAILED: "PRODUCT_FIND_ALL_REQUEST_FAILED",
  PRODUCT_QUERY_REQUEST: "PRODUCT_QUERY_REQUEST",
  PRODUCT_QUERY_REQUEST_SUCCEED: "PRODUCT_QUERY_REQUEST_SUCCEED",
  PRODUCT_QUERY_REQUEST_FAILED: "PRODUCT_QUERY_REQUEST_FAILED"
};

export const productBrandActionTypes = {
  "PRODUCT-BRAND_FIND_ALL_REQUEST": "PRODUCT-BRAND_FIND_ALL_REQUEST",
  "PRODUCT-BRAND_FIND_BY_ID_REQUEST": "PRODUCT-BRAND_FIND_BY_ID_REQUEST",
  "PRODUCT-BRAND_QUERY_REQUEST": "PRODUCT-BRAND_QUERY_REQUEST",
  "PRODUCT-BRAND_REQUEST_SUCCEED": "PRODUCT-BRAND_REQUEST_SUCCEED",
  "PRODUCT-BRAND_REQUEST_FAILED": "PRODUCT-BRAND_REQUEST_FAILED",
  "PRODUCT-BRAND_DELETE_REQUEST": "PRODUCT-BRAND_DELETE_REQUEST",
  "PRODUCT-BRAND_DELETE_SUCCEED": "PRODUCT-BRAND_DELETE_SUCCEED",
  "PRODUCT-BRAND_RESET_DATA": "PRODUCT-BRAND_RESET_DATA"
};

export const productBrandUnitActionTypes = {
  "PRODUCT-BRAND-UNIT_FIND_ALL_REQUEST": "PRODUCT-BRAND-UNIT_FIND_ALL_REQUEST",
  "PRODUCT-BRAND-UNIT_FIND_BY_ID_REQUEST": "PRODUCT-BRAND-UNIT_FIND_BY_ID_REQUEST",
  "PRODUCT-BRAND-UNIT_QUERY_REQUEST": "PRODUCT-BRAND-UNIT_QUERY_REQUEST",
  "PRODUCT-BRAND-UNIT_REQUEST_SUCCEED": "PRODUCT-BRAND-UNIT_REQUEST_SUCCEED",
  "PRODUCT-BRAND-UNIT_REQUEST_FAILED": "PRODUCT-BRAND-UNIT_REQUEST_FAILED",
  "PRODUCT-BRAND-UNIT_DELETE_REQUEST": "PRODUCT-BRAND-UNIT_DELETE_REQUEST",
  "PRODUCT-BRAND-UNIT_DELETE_SUCCEED": "PRODUCT-BRAND-UNIT_DELETE_SUCCEED",
  "PRODUCT-BRAND-UNIT_RESET_DATA": "PRODUCT-BRAND-UNIT_RESET_DATA"
};

export const sessionActionTypes = {
  AUTHENTICATION_REQUEST_INITIATED: "AUTHENTICATION_REQUEST_INITIATED",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
  UNAUTHENTICATE_SUCCESS: "UNAUTHENTICATE_SUCCESS",
  UNAUTHENTICATE_REQUEST_INITIATED: "UNAUTHENTICATE_REQUEST_INITIATED",
  AUTHENTICATION_REQUEST_FAILED: "AUTHENTICATION_REQUEST_FAILED"
};

export const sellerProductActionTypes = {
  "SELLER-PRODUCT_QUERY_REQUEST": "SELLER-PRODUCT_QUERY_REQUEST",
  "SELLER-PRODUCT_FIND_ALL_REQUEST": "SELLER-PRODUCT_FIND_ALL_REQUEST",
  "SELLER-PRODUCT_FIND_BY_ID_REQUEST": "SELLER-PRODUCT_FIND_BY_ID_REQUEST",
  "SELLER-PRODUCT_CREATE_REQUEST": "SELLER-PRODUCT_CREATE_REQUEST",
  "SELLER-PRODUCT_UPDATE_REQUEST": "SELLER-PRODUCT_UPDATE_REQUEST",
  "SELLER-PRODUCT_DELETE_REQUEST": "SELLER-PRODUCT_DELETE_REQUEST",
  "SELLER-PRODUCT_SUCCEED": "SELLER-PRODUCT_SUCCEED",
  "SELLER-PRODUCT_FAILED": "SELLER-PRODUCT_FAILED",
  "SELLER-PRODUCT_DELETE_SUCCEED": "SELLER-PRODUCT_DELETE_SUCCEED"
};
